/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        raleway: ["Raleway", "sans-serif"],
        lato: ["Lato", "sans-serif"],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        myDark: {
          primary: "#FFA500",
          "primary-content": "#000000",
          secondary: "#FFC96F",
          "secondary-content": "#000000",
          accent: "#FFEC9E",
          "accent-content": "#FFFFFF",
          neutral: "#FFE8C8",
          "neutral-content": "#FFFFFF",
          "base-100": "#120000",
          "base-200": "#FDEBD0",
          "base-300": "#000000",
          "base-content": "#F8F8FF",
          info: "#00A7E6",
          "info-content": "#FFFFFF",
          success: "#6ABE45",
          "success-content": "#FFFFFF",
          warning: "#F97316",
          "warning-content": "#FFFFFF",
          error: "#F54748",
          "error-content": "#FFFFFF",
          "text-primary": "#120000",
          "text-secondary": "#120000",
        },
      },
      {
        myLight: {
          primary: "#FFA500",
          "primary-content": "#000000",
          secondary: "#FFC96F",
          "secondary-content": "#000000",
          accent: "#FFEC9E",
          "accent-content": "#000000",
          neutral: "#FFE8C8",
          "neutral-content": "#000000",
          "base-100": "#F8F8FF",
          "base-200": "#F0F0F0",
          "base-300": "#E8E8E8",
          "base-content": "#000000",
          info: "#00A7E6",
          "info-content": "#FFFFFF",
          success: "#6ABE45",
          "success-content": "#FFFFFF",
          warning: "#F97316",
          "warning-content": "#FFFFFF",
          error: "#F54748",
          "error-content": "#FFFFFF",
        },
      },
    ],
  },
};
